name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-and-test:
    name: Build the project
    runs-on: ubuntu-latest
    # if: github.event_name == 'pull_request'
    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run eslint
        run: npm run lint
      - name: Print Variable
        run: |
          echo "Variable Value: ${{ secrets.TEST_DB_HOST }}"
          echo "Variable Value: ${{ secrets.TEST_DB_PORT }}"
          echo "Variable Value: ${{ secrets.TEST_DB_USERNAME }}"
          echo "Variable Value: ${{ secrets.TEST_DB_PASSWORD }}"
          echo "Variable Value: ${{ secrets.TEST_DB_NAME }}"
          echo "Variable Value: ${{ secrets.REFRESH_TOKEN_SECRET }}"
          echo "Variable Value: ${{ secrets.JWKS_URI }}"
          echo "Variable Value: ${{ secrets.PRIVATE_KEY }}"
      - name: Test and coverage
        run: npm run test
        env:
          DB_HOST: ${{ secrets.TEST_DB_HOST }}
          DB_PORT: ${{ secrets.TEST_DB_PORT }}
          DB_USER: ${{ secrets.TEST_DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          DB_NAME: ${{ secrets.TEST_DB_NAME }}
          REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
          JWKS_URI: ${{ secrets.JWKS_URI }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      - name: Build-ts
        run: npm run build
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-push-docker:
    name: Build and Push Docker Image
    needs: build-and-test
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: codersgyan/mernstack_auth_service
      IMAGE_TAG: build-${{ github.run_number }}
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f docker/prod/Dockerfile .
      - name: Push Docker image to Docker Hub
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
